require('dotenv').config();
const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),crypto=require('crypto'),QRCode=require('qrcode');
const app=express(); app.use(cors()); app.use(express.json({limit:'1mb'}));
const db=new Database(process.env.DATABASE_FILE||'./data/vvip.db'); db.pragma('journal_mode = WAL');
const schema=`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,mobile TEXT UNIQUE NOT NULL,name TEXT,role TEXT NOT NULL DEFAULT 'customer',password_hash TEXT,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS otp(id INTEGER PRIMARY KEY AUTOINCREMENT,mobile TEXT NOT NULL,code_hash TEXT NOT NULL,expires_at INTEGER,used INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,price REAL NOT NULL,unit TEXT NOT NULL,halal INTEGER DEFAULT 1,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sellers(id TEXT PRIMARY KEY,user_id TEXT,business_name TEXT NOT NULL,fssai_no TEXT NOT NULL,pan TEXT NOT NULL,gst_status TEXT DEFAULT 'Not Registered',gstin TEXT,halal_status TEXT DEFAULT 'Pending',status TEXT DEFAULT 'Pending Review',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,user_id TEXT,source TEXT NOT NULL,status TEXT NOT NULL,total REAL NOT NULL,halal_order INTEGER DEFAULT 1,payment_method TEXT DEFAULT 'COD',payment_status TEXT DEFAULT 'Pending',delivery_address TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id TEXT PRIMARY KEY,order_id TEXT,product_id TEXT,name TEXT,quantity REAL,unit_price REAL,halal INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS delivery_partners(id TEXT PRIMARY KEY,user_id TEXT,name TEXT,mobile TEXT UNIQUE,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS delivery_assignments(id TEXT PRIMARY KEY,order_id TEXT UNIQUE,partner_id TEXT,status TEXT DEFAULT 'Assigned',qr_hash TEXT,qr_token TEXT,picked_up_at TEXT,delivered_at TEXT);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,action TEXT,entity TEXT,entity_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`;
db.exec(schema);
const products=[['fresh-chicken','Fresh Chicken',260,'kg'],['desi-chicken','Desi Chicken',2800,'piece'],['boneless-chicken','Boneless Chicken',360,'kg'],['chicken-leg','Chicken Leg',340,'kg'],['chicken-breast','Chicken Breast',360,'kg'],['mutton','Mutton',850,'kg'],['mutton-chaap','Mutton Chaap',900,'kg'],['mutton-boneless','Mutton Boneless',1200,'kg'],['mutton-keema','Mutton Keema',900,'kg'],['mutton-raan','Mutton Raan',1000,'kg'],['eggs','Eggs',7,'piece'],['chicken-kaleji','Chicken Kaleji',240,'kg'],['mutton-kaleji','Mutton Kaleji',900,'kg']];
const ins=db.prepare('INSERT OR IGNORE INTO products(id,name,price,unit,halal) VALUES(?,?,?,?,1)'); products.forEach(p=>ins.run(...p));
[['marketplace','false'],['online_payment','true'],['cod','true'],['delivery_tracking','true'],['seller_registration','false'],['halal_labeling','true']].forEach(([k,v])=>db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)').run(k,v));
function token(u){return jwt.sign({sub:u.id,role:u.role,mobile:u.mobile},process.env.JWT_SECRET||'DEV_CHANGE_ME', {expiresIn:'7d'})}
function auth(req,res,next){const h=req.headers.authorization||'';try{req.user=jwt.verify(h.replace(/^Bearer /,''),process.env.JWT_SECRET||'DEV_CHANGE_ME');next()}catch(e){res.status(401).json({error:'Authentication required'})}}
function roles(...rs){return (req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({error:'Forbidden'})}
function audit(user,action,entity,id){db.prepare('INSERT INTO audit(user_id,action,entity,entity_id) VALUES(?,?,?,?)').run(user,action,entity,id)}
app.get('/api/health',(q,s)=>s.json({status:'ok',version:'5.0.0',brand:'VVIP MARKET PALACE'}));
app.get('/api/config',(q,s)=>{const rows=db.prepare('SELECT key,value FROM settings').all(); const x=Object.fromEntries(rows.map(r=>[r.key,r.value==='true']));s.json({brand:'VVIP MARKET PALACE',tagline:'Fresh. Trusted. Delivered.',city:'Ahmedabad',...x})});
app.get('/api/products',(q,s)=>s.json({products:db.prepare('SELECT * FROM products WHERE active=1 ORDER BY name').all()}));
app.post('/api/auth/request-otp',(req,res)=>{const mobile=String(req.body.mobile||'').replace(/\D/g,'');if(!/^\d{10}$/.test(mobile))return res.status(400).json({error:'Valid 10-digit mobile required'});const code=String(Math.floor(100000+Math.random()*900000));const hash=bcrypt.hashSync(code,10);db.prepare('INSERT INTO otp(mobile,code_hash,expires_at) VALUES(?,?,?)').run(mobile,hash,Date.now()+5*60*1000);res.json({message:'OTP created',dev_otp:process.env.OTP_DEV_MODE==='true'?code:undefined})});
app.post('/api/auth/verify-otp',(req,res)=>{const mobile=String(req.body.mobile||'').replace(/\D/g,''),code=String(req.body.otp||'');const row=db.prepare('SELECT * FROM otp WHERE mobile=? AND used=0 ORDER BY id DESC LIMIT 1').get(mobile);if(!row||Date.now()>row.expires_at||!bcrypt.compareSync(code,row.code_hash))return res.status(400).json({error:'Invalid or expired OTP'});db.prepare('UPDATE otp SET used=1 WHERE id=?').run(row.id);let u=db.prepare('SELECT * FROM users WHERE mobile=?').get(mobile);if(!u){u={id:crypto.randomUUID(),mobile,name:'',role:'customer'};db.prepare('INSERT INTO users(id,mobile,name,role) VALUES(?,?,?,?)').run(u.id,u.mobile,u.name,u.role)}res.json({token:token(u),user:u})});
app.post('/api/orders',auth,(req,res)=>{const {items=[],source='website',payment_method='COD',delivery_address=''}=req.body;if(!Array.isArray(items)||!items.length)return res.status(400).json({error:'Cart is empty'});let total=0;const normalized=[];for(const i of items){const p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(i.product_id);if(!p)return res.status(400).json({error:'Invalid product'});const qty=Number(i.quantity);if(!(qty>0))return res.status(400).json({error:'Invalid quantity'});total+=p.price*qty;normalized.push({p,qty})}const id='#VVIP'+crypto.randomInt(100000,999999);const tx=db.transaction(()=>{db.prepare('INSERT INTO orders(id,user_id,source,status,total,halal_order,payment_method,delivery_address) VALUES(?,?,?,?,?,1,?,?)').run(id,req.user.sub,source,'New',total,payment_method,delivery_address);const oi=db.prepare('INSERT INTO order_items(id,order_id,product_id,name,quantity,unit_price,halal) VALUES(?,?,?,?,?,?,1)');normalized.forEach(x=>oi.run(crypto.randomUUID(),id,x.p.id,x.p.name,x.qty,x.p.price));audit(req.user.sub,'create','order',id)});tx();res.status(201).json(db.prepare('SELECT * FROM orders WHERE id=?').get(id))});
app.get('/api/orders',auth,(req,res)=>{let rows;if(req.user.role==='customer')rows=db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC').all(req.user.sub);else rows=db.prepare('SELECT * FROM orders ORDER BY created_at DESC').all();safify(rows);res.json({orders:rows})});
function safify(rows){return rows}
app.get('/api/orders/:id',auth,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(req.params.id);if(!o)return res.sendStatus(404);if(req.user.role==='customer'&&o.user_id!==req.user.sub)return res.sendStatus(403);o.items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);o.delivery=db.prepare('SELECT da.*,dp.name partner_name,dp.mobile partner_mobile FROM delivery_assignments da LEFT JOIN delivery_partners dp ON dp.id=da.partner_id WHERE da.order_id=?').get(o.id)||null;res.json(o)});
app.patch('/api/orders/:id/status',auth,roles('admin','delivery'),(req,res)=>{const allowed=['New','Accepted','Preparing','Ready','Assigned','Out for Delivery','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});db.prepare('UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(req.body.status,req.params.id);audit(req.user.sub,'status_change','order',req.params.id);res.json({ok:true})});
app.post('/api/delivery/assign',auth,roles('admin'),(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=?').get(req.body.order_id);const p=db.prepare('SELECT * FROM delivery_partners WHERE id=? AND active=1').get(req.body.partner_id);if(!o||!p)return res.status(400).json({error:'Order or delivery partner not found'});const raw=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(raw).digest('hex'),id=crypto.randomUUID();db.prepare('INSERT OR REPLACE INTO delivery_assignments(id,order_id,partner_id,status,qr_hash,qr_token) VALUES(?,?,?,?,?,?)').run(id,o.id,p.id,'Assigned',hash,raw);db.prepare('UPDATE orders SET status="Assigned",updated_at=CURRENT_TIMESTAMP WHERE id=?').run(o.id);res.json({id,order_id:o.id,qr_token:raw,halal:true})});
app.get('/api/delivery/qr/:orderId',auth,roles('admin','delivery'),async(req,res)=>{const d=db.prepare('SELECT * FROM delivery_assignments WHERE order_id=?').get(req.params.orderId);if(!d)return res.sendStatus(404);const payload=JSON.stringify({order_id:d.order_id,token:d.qr_token});res.type('text/plain').send(await QRCode.toDataURL(payload))});
app.post('/api/delivery/verify-qr',auth,roles('admin','delivery'),(req,res)=>{const d=db.prepare('SELECT * FROM delivery_assignments WHERE order_id=?').get(req.body.order_id);if(!d)return res.status(404).json({error:'Assignment not found'});const h=crypto.createHash('sha256').update(String(req.body.token||'')).digest('hex');if(h!==d.qr_hash)return res.status(400).json({error:'Invalid QR token'});const o=db.prepare('SELECT id,status,total,payment_status FROM orders WHERE id=?').get(d.order_id);res.json({valid:true,halal:true,order:o})});
app.get('/api/admin/stats',auth,roles('admin'),(req,res)=>{const count=q=>db.prepare(q).get().n||0;const sales=db.prepare('SELECT COALESCE(SUM(total),0) n FROM orders WHERE status<>"Cancelled"').get().n;res.json({orders:count('SELECT COUNT(*) n FROM orders'),pending:count('SELECT COUNT(*) n FROM orders WHERE status NOT IN ("Delivered","Cancelled")'),delivered:count('SELECT COUNT(*) n FROM orders WHERE status="Delivered"'),customers:count('SELECT COUNT(*) n FROM users WHERE role="customer"'),sales:Number(sales)})});
app.post('/api/admin/settings',auth,roles('admin'),(req,res)=>{for(const [k,v] of Object.entries(req.body||{})){if(!['marketplace','online_payment','cod','delivery_tracking','seller_registration','halal_labeling'].includes(k))continue;db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').run(k,String(!!v));}res.json({ok:true})});
app.post('/api/sellers',auth,(req,res)=>{const x=req.body;if(!x.fssai_no||!x.pan||!x.business_name)return res.status(400).json({error:'Business name, PAN and FSSAI are required'});const id=crypto.randomUUID();db.prepare('INSERT INTO sellers(id,user_id,business_name,fssai_no,pan,gst_status,gstin,halal_status) VALUES(?,?,?,?,?,?,?,?)').run(id,req.user.sub,x.business_name,x.fssai_no,x.pan,x.gst_status||'Not Registered',x.gstin||null,x.halal_status||'Pending');res.status(201).json(db.prepare('SELECT * FROM sellers WHERE id=?').get(id))});
app.get('/api/sellers',auth,roles('admin'),(q,s)=>s.json({sellers:db.prepare('SELECT * FROM sellers ORDER BY created_at DESC').all()}));
app.post('/api/delivery/partners',auth,roles('admin'),(req,res)=>{const id=crypto.randomUUID();db.prepare('INSERT INTO delivery_partners(id,user_id,name,mobile) VALUES(?,?,?,?)').run(id,req.body.user_id||null,req.body.name,req.body.mobile);res.status(201).json(db.prepare('SELECT * FROM delivery_partners WHERE id=?').get(id))});
app.get('/api/delivery/partners',auth,roles('admin'),(q,s)=>s.json({partners:db.prepare('SELECT * FROM delivery_partners WHERE active=1').all()}));
// Production hardening: bootstrap admin endpoint removed. Provision admin out-of-band.
app.listen(process.env.PORT||3000,()=>console.log('VVIP MARKET PALACE API running'));
